# Use this schema as reference for the global state of the app and
# to figure out the structure of a tutorial JSON file
type AppState {
  initialContent:
  tutorialState: {
    selectedTutorial: String!
    currentStep: Number!
    currentOutput: Output!
  }
  editorState: {
    editor: {
      selectedTutorial: String!
      selectedStep: Number!
      isSaved: Boolean!
    }
    # Editable tutorial data structure
    tutorialInstance: Tutorial!  
   }
}

type Tutorial {
  name: String!
  description: String!
  instructions: [Instruction]
}

type Instruction {
  title: String!
  hint: String!
  output: Output!
  content: [InstructionContent]!
  solution: String!
}

type Output {
  status: String!
  terminalMsg: String?
  droneState: DroneState!
}

type InstructionContent {
  type: String!
  value: String!
}

type DroneState {
  pitch: Number
  yaw: Number
  roll: Number
  armed: Boolean
  velocity: Number
  direction: String
  altitude: Number
}
